### ISSUE TITLE
Fatal Error when using m2m Toolset Common branch

### ISSUE THREAD

**Issue by kmgalanakis** [zaantar/tcl-status#3]
When the `m2m` Toolset Common branch is installed via composer, while the `Toolset Common Status` is enabled, on page reload I get the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Toolset_Wpml_Utils::is_wpml_active() in /srv/www/otgs3.wordpress/htdocs/wp-content/plugins/tcl-status/tcl-status.php:265
Stack trace:
#0 /srv/www/otgs3.wordpress/htdocs/wp-content/plugins/tcl-status/tcl-status.php(84): TclStatus\Main->add_m2m_node(Object(WP_Admin_Bar), 'tcl-status')
#1 /srv/www/otgs3.wordpress/htdocs/wp-includes/class-wp-hook.php(298): TclStatus\Main->modify_admin_bar(Object(WP_Admin_Bar))
#2 /srv/www/otgs3.wordpress/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#3 /srv/www/otgs3.wordpress/htdocs/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#4 /srv/www/otgs3.wordpress/htdocs/wp-includes/admin-bar.php(83): do_action_ref_array('admin_bar_menu', Array)
#5 /srv/www/otgs3.wordpress/htdocs/wp-includes/class-wp-hook.php(298): wp_admin_bar_render('')
#6 /srv/www/otgs3.wordpress/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#7 /srv/www/otgs3.wordpress/htdocs/wp-includes/plugin.php(453): W in /srv/www/otgs3.wordpress/htdocs/wp-content/plugins/tcl-status/tcl-status.php on line 265
```

**Comment by zaantar** [comment]
@kmgalanakis, please pull from master and try again. The issue should be fixed. I have temporarily disabled the m2m/WPML interop part, since it's still under development in the m2m API.
